ALTER TABLE "CharacterSheet" ADD COLUMN "hpActual" INTEGER DEFAULT 0;
ALTER TABLE "CharacterSheet" ADD COLUMN "hpMax" INTEGER DEFAULT 0;
ALTER TABLE "CharacterSheet" ADD COLUMN "hpPerLevel" INTEGER DEFAULT 0;